services:
  db-test:
    image: teleivo/openmrs-platform-mysql:2.0.0
    container_name: openmrs-platform-mysql-test
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${TEST_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${TEST_MYSQL_DATABASE}
    volumes:
      - openmrs-db-data-test:/var/lib/mysql
    networks:
      test-net:
        aliases:
          - db

  openmrs-test:
    image: teleivo/openmrs-module-radiology:latest
    container_name: openmrs-module-radiology-test
    restart: unless-stopped
    depends_on:
      - db-test
    ports:
      - "127.0.0.1:${TEST_PORT}:8080"
    environment:
      MYSQL_HOST: ${TEST_MYSQL_HOST}
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: ${TEST_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${TEST_MYSQL_DATABASE}

      PACS_HOST: ${PACS_HOST}
      PACS_ADMIN_USER: ${PACS_ADMIN_USER}
      PACS_ADMIN_PASSWORD: ${PACS_ADMIN_PASSWORD}
      PACS_WADO_URL: ${PACS_WADO_URL}
    volumes:
      - openmrs-app-data-test:/usr/local/tomcat/.OpenMRS
      - ./legacyui-1.2.omod:/usr/local/tomcat/.OpenMRS/modules/legacyui-1.2.omod
      - ./webservices.rest-2.24.0.omod:/usr/local/tomcat/.OpenMRS/modules/webservices.rest-2.24.0.omod
    networks:
      - test-net

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube-server
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - test-net
    volumes:
      - sonarqube-data-test:/opt/sonarqube/data
      - sonarqube-extensions-test:/opt/sonarqube/extensions
      - sonarqube-logs-test:/opt/sonarqube/logs

volumes:
  openmrs-db-data-test:
  openmrs-app-data-test:
  sonarqube-data-test:
  sonarqube-extensions-test:
  sonarqube-logs-test:

networks:
  test-net:
    driver: bridge