version: "3.8"

services:
  db-prod:
    image: teleivo/openmrs-platform-mysql:2.0.0
    container_name: openmrs-platform-mysql-prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PROD_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PROD_MYSQL_DATABASE}
    volumes:
      - openmrs-db-data-prod:/var/lib/mysql
    networks:
      prod-net:
        aliases:
          - db

  openmrs-prod:
    image: teleivo/openmrs-module-radiology:latest
    container_name: openmrs-module-radiology-prod
    restart: always
    depends_on:
      - db-prod
    ports:
      - "127.0.0.1:${PROD_PORT}:8080"
    environment:
      MYSQL_HOST: ${PROD_MYSQL_HOST}
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: ${PROD_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PROD_MYSQL_DATABASE}
    volumes:
      - openmrs-app-data:/usr/local/tomcat/.OpenMRS
      - ./legacyui-1.2.omod:/usr/local/tomcat/.OpenMRS/modules/legacyui-1.2.omod
      - ./webservices.rest-2.17.omod:/usr/local/tomcat/.OpenMRS/modules/webservices.rest-2.17.omod
    networks:
      - prod-net

volumes:
  openmrs-db-data-prod:
  openmrs-app-data-prod:

networks:
  prod-net:
    driver: bridge