version: "3.8"

services:
  db-prod:
    image: teleivo/openmrs-platform-mysql:2.0.0
    container_name: openmrs-platform-mysql-prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PROD_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PROD_MYSQL_DATABASE}
    volumes:
      - openmrs-db-data-prod:/var/lib/mysql
    networks:
      prod-net:
        aliases:
          - db

  openmrs-prod:
    image: teleivo/openmrs-module-radiology:latest
    container_name: openmrs-module-radiology-prod
    restart: always
    depends_on:
      - db-prod
    ports:
      - "127.0.0.1:${PROD_PORT}:8080"
    environment:
      MYSQL_HOST: ${PROD_MYSQL_HOST}
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: ${PROD_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PROD_MYSQL_DATABASE}

      PACS_HOST: ${PACS_HOST}
      PACS_ADMIN_USER: ${PACS_ADMIN_USER}
      PACS_ADMIN_PASSWORD: ${PACS_ADMIN_PASSWORD}
      PACS_WADO_URL: ${PACS_WADO_URL}
    volumes:
      - openmrs-app-data:/usr/local/tomcat/.OpenMRS
      - ./legacyui-1.2.omod:/usr/local/tomcat/.OpenMRS/modules/legacyui-1.2.omod
      - ./webservices.rest-2.24.0.omod:/usr/local/tomcat/.OpenMRS/modules/webservices.rest-2.24.0.omod
    networks:
      - prod-net

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube-server
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - backend-net
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-logs:/opt/sonarqube/logs

volumes:
  openmrs-db-data-prod:
  openmrs-app-data-prod:
  sonarqube-data-prod:
  sonarqube-extensions-prod:
  sonarqube-logs-prod:

networks:
  prod-net:
    driver: bridge