version: "3.8"

services:
  db:
    image: teleivo/openmrs-platform-mysql:2.0.0
    container_name: openmrs-radiology-test-db
    restart: "no"
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test_root_password
      MYSQL_USER: openmrs_test
      MYSQL_PASSWORD: openmrs_test_password
      MYSQL_DATABASE: openmrs_test_db
    volumes:
      - ./acceptanceTest/resources/demo-data.sql:/docker-entrypoint-initdb.d/demo-data.sql
    networks:
      - test-net

  openmrs:
    image: teleivo/openmrs-module-radiology:latest
    container_name: openmrs-radiology-test-app
    restart: "no"
    depends_on:
      - db
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: openmrs_test
      MYSQL_PASSWORD: openmrs_test_password
      MYSQL_DATABASE: openmrs_test_db
    networks:
      - test-net

networks:
  test-net:
    driver: bridge