version: "3.8"

services:
  db-test:
    image: teleivo/openmrs-platform-mysql:2.0.0
    container_name: openmrs-platform-mysql-test
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - openmrs-db-data-test:/var/lib/mysql
    networks:
      - test-net

  openmrs-test:
    image: teleivo/openmrs-module-radiology:latest
    container_name: openmrs-module-radiology-test
    restart: unless-stopped
    depends_on:
      - db-test
    ports:
      - "127.0.0.1:${TEST_PORT}:8080"
    environment:
      MYSQL_HOST: db-test
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - openmrs-app-data-test:/usr/local/tomcat/.OpenMRS
    networks:
      - test-net

volumes:
  openmrs-db-data-test:
  openmrs-app-data-test:

networks:
  test-net:
    driver: bridge